pub const estate_control_plane =
    \\CREATE TABLE IF NOT EXISTS ziac_accounts (google_subject STRING PRIMARY KEY, identity_hash BYTES NOT NULL CHECK (length(identity_hash) = 32), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), disabled_at TIMESTAMPTZ NULL);
    \\CREATE TABLE IF NOT EXISTS ziac_identity_sessions (session_digest BYTES PRIMARY KEY CHECK (length(session_digest) = 32), google_subject STRING NOT NULL REFERENCES ziac_accounts (google_subject), expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
    \\CREATE INDEX IF NOT EXISTS ziac_identity_sessions_subject_idx ON ziac_identity_sessions (google_subject, expires_at DESC);
    \\CREATE TABLE IF NOT EXISTS ziac_entitlements (google_subject STRING PRIMARY KEY REFERENCES ziac_accounts (google_subject), tier STRING NOT NULL CHECK (tier IN ('free', 'pro')), active BOOL NOT NULL, source STRING NOT NULL, source_customer_hash BYTES NULL, expires_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
    \\CREATE TABLE IF NOT EXISTS ziac_gcp_connections (connection_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), google_subject STRING NOT NULL REFERENCES ziac_accounts (google_subject), project_id STRING NOT NULL, status STRING NOT NULL CHECK (status IN ('connected', 'disconnected')), credential_ciphertext BYTES NOT NULL, credential_kms_key_version STRING NOT NULL, credential_sha256 BYTES NOT NULL CHECK (length(credential_sha256) = 32), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ NULL, UNIQUE (google_subject, project_id));
    \\CREATE TABLE IF NOT EXISTS ziac_google_credentials (google_subject STRING PRIMARY KEY REFERENCES ziac_accounts (google_subject), credential_ciphertext BYTES NOT NULL, credential_kms_key_version STRING NOT NULL, credential_sha256 BYTES NOT NULL CHECK (length(credential_sha256) = 32), rotated_at TIMESTAMPTZ NOT NULL DEFAULT now());
    \\CREATE TABLE IF NOT EXISTS ziac_oauth_challenges (state_digest BYTES PRIMARY KEY CHECK (length(state_digest) = 32), nonce_digest BYTES NOT NULL CHECK (length(nonce_digest) = 32), verifier_digest BYTES NOT NULL CHECK (length(verifier_digest) = 32), redirect_uri STRING NOT NULL, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
    \\CREATE TABLE IF NOT EXISTS ziac_estate_audit (event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), google_subject STRING NOT NULL, action STRING NOT NULL, resource_id STRING NOT NULL, outcome STRING NOT NULL CHECK (outcome IN ('allowed', 'denied')), request_digest BYTES NULL, detail JSONB NOT NULL DEFAULT '{}'::JSONB);
    \\CREATE INDEX IF NOT EXISTS ziac_estate_audit_subject_time_idx ON ziac_estate_audit (google_subject, occurred_at DESC);
;

pub const billing_intelligence =
    \\CREATE TABLE IF NOT EXISTS ziac_billing_sources (source_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), connection_id UUID NULL REFERENCES ziac_gcp_connections (connection_id), source_kind STRING NOT NULL CHECK (source_kind IN ('self_host', 'customer_connection')), owner_project_id STRING NOT NULL, billing_project_id STRING NOT NULL, export_table STRING NOT NULL, location STRING NULL, currency STRING NOT NULL CHECK (length(currency) = 3), enabled BOOL NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (owner_project_id, export_table));
    \\CREATE TABLE IF NOT EXISTS ziac_billing_ingestion_runs (run_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source_id UUID NOT NULL REFERENCES ziac_billing_sources (source_id), window_start TIMESTAMPTZ NOT NULL, window_end TIMESTAMPTZ NOT NULL, status STRING NOT NULL CHECK (status IN ('running', 'complete', 'failed')), query_job_id STRING NULL, billed_total_micros INT8 NULL, attributed_total_micros INT8 NULL, unattributed_total_micros INT8 NULL, coverage_basis_points INT4 NULL CHECK (coverage_basis_points BETWEEN 0 AND 10000), error_code STRING NULL, started_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ NULL, UNIQUE (source_id, window_start, window_end));
    \\CREATE TABLE IF NOT EXISTS ziac_billing_resource_costs (run_id UUID NOT NULL REFERENCES ziac_billing_ingestion_runs (run_id) ON DELETE CASCADE, resource_id STRING NOT NULL, google_global_name STRING NOT NULL, amount_micros INT8 NOT NULL, currency STRING NOT NULL CHECK (length(currency) = 3), attribution STRING NOT NULL CHECK (attribution IN ('global_name', 'ziac_label')), observed_at TIMESTAMPTZ NOT NULL, PRIMARY KEY (run_id, resource_id, google_global_name));
    \\CREATE INDEX IF NOT EXISTS ziac_billing_runs_source_window_idx ON ziac_billing_ingestion_runs (source_id, window_end DESC);
;
